<template>
    <slot></slot>
</template>

<script>
export default {
  data() {
    return {data: {
      groups: [
        "Milks & Diaries",
        "Coffees & Teas",
        "Pet Foods",
        "Meats",
        "Vegetables",
        "Fruits",
      ],
      promotions: [
        {
          id: 1,
          title: "Everyday Fresh & Clean with Our Products",
          color: "#F0E8D5",
          image: new URL("../assets/images/Cms-04 1.png", import.meta.url),
        },
        {
          id: 2,
          title: "Make your Breakfast Healthy and Easy",
          color: "#F3E8E8",
          image: new URL("../assets/images/Cat-01 1.png", import.meta.url),
        },
        {
          id: 3,
          title: "The best Organic Products Online",
          color: "#E7EAF3",
          image: new URL("../assets/images/Cms-03 1.png", import.meta.url),
        },
      ],
      categories: [
        {
          id: 1,
          group: "Milks & Diaries",
          name: "Coke & Milk",
          color: "#F2FCE4",
          image: new URL("../assets/images/Hamberger.png", import.meta.url),
        },
        {
          id: 2,
          group: "Fruits",
          name: "Peach",
          color: "#FFFCEB",
          image: new URL("../assets/images/Peach.png", import.meta.url),
        },
        {
          id: 3,
          group: "Fruits",
          name: "Organic Kiwi",
          color: "#ECFFEC",
          image: new URL("../assets/images/Kiwi.png", import.meta.url),
        },
        {
          id: 4,
          group: "Fruits",
          name: "Red Apple",
          color: "#FEEFEA",
          image: new URL("../assets/images/RedApple.png", import.meta.url),
        },
        {
          id: 5,
          group: "Coffees & Teas",
          name: "Snack",
          color: "#FFF3EB",
          image: new URL("../assets/images/Snack.png", import.meta.url),
        },
        {
          id: 6,
          group: "Coffees & Teas",
          name: "Black plum",
          color: "#FFF3FF",
          image: new URL("../assets/images/BlackPlum.png", import.meta.url),
        },
        {
          id: 7,
          group: "Coffees & Teas",
          name: "Vegetables",
          color: "#F2FCE4",
          image: new URL("../assets/images/Vegetable.png", import.meta.url),
        },
        {
          id: 8,
          group: "Coffees & Teas",
          name: "Headphone",
          color: "#FFFCEB",
          image: new URL("../assets/images/Headphone.png", import.meta.url),
        },
        {
          id: 9,
          group: "Coffees & Teas",
          name: "Sweet",
          color: "#F2FCE4",
          image: new URL("../assets/images/Sweet.png", import.meta.url),
        },
        {
          id: 10,
          group: "Coffees & Teas",
          name: "Orange",
          color: "#FFF3FF",
          image: new URL("../assets/images/Orange.png", import.meta.url),
        },
      ],
      products: [
        {
          id: 1,
          tag: "Hot",
          image: new URL("../assets/images/1 902.png", import.meta.url),
          category: "Fruits",
          name: "Kompung Spue Corn",
          rate: 3,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 50,
        },
        {
          id: 2,
          tag: "Sale",
          image: new URL("../assets/images/3 389454.png", import.meta.url),
          category: "Drink",
          name: "Porsat Orange",
          rate: 4,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 100,
        },
        {
          id: 3,
          tag: "-17%",
          image: new URL("../assets/images/5 7.png", import.meta.url),
          category: "Coffees & Teas",
          name: "Kampot Chili",
          rate: 5,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 400,
          discountPercentage: 17,
          discountPrice: 250,
        },
        {
          id: 4,
          tag: "-55%",
          image: new URL("../assets/images/8 1.png", import.meta.url),
          category: "Vegetable",
          name: "Meat Superman",
          rate: 4,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 50,
          discountPercentage: 17,
          discountPrice: 25,
        },
        {
          id: 5,
          tag: "",
          image: new URL("../assets/images/9 1.png", import.meta.url),
          category: "Coffees & Teas",
          name: "Japanese Fish",
          rate: 5,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 40,
        },
        {
          id: 6,
          tag: "",
          image: new URL("../assets/images/11 1.png", import.meta.url),
          category: "Snack",
          name: "Takoa Stack",
          rate: 4,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 150,
        },
        {
          id: 7,
          tag: "",
          image: new URL("../assets/images/12 1.png", import.meta.url),
          category: "Coffees & Teas",
          name: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
          rate: 5,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 150,
        },
        {
          id: 8,
          tag: "",
          image: new URL("../assets/images/16 1.png", import.meta.url),
          category: "Fruits",
          name: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
          rate: 4,
          description: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. As of March 2023, Apple is the world's largest company by market capitalization, and with US$394.3 billion the largest technology company by 2022 revenue.",
          sellPrice: 300,
          discountPercentage: 17,
          discountPrice: 150,
        },
      ],
    }};
  },
  provide() {
    return {
        data: this.data,
    }
  }
};
</script>
